### ISSUE TITLE
Getting error in initial UI loading and user login.

### ISSUE THREAD

**Issue by ma-sattari** [ibi-group/datatools-ui#58]
Hi,

It is NOT a bug but I couldn't find any user group to ask about my problem.

I am getting following .js error when loading the UI .

![conveyal error](https://user-images.githubusercontent.com/25766089/37267240-fb23c168-25cf-11e8-8c75-61c255ed6e34.jpg)

I also got an error when trying to login as following snapshot:
![conveyal error2](https://user-images.githubusercontent.com/25766089/37267248-0acae556-25d0-11e8-80f3-cac19e740ca2.jpg)

The datatools-server is running on localhost:4000 and I have double checked env.yml files (server and UI ) but unable to  find the source of problem.
I Also have read the latest doc at:
http://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment/

OS: Windows 10
node version: 6.13.1

Any help would be appreciated.

**Comment by MaSattari** [comment]
Hi again,

It seems Auth0 has deprecated some methods in Authentication API and also something related to Auth0-lock.js has been changed, does anyone has problem with getting data from _Auth0_Domain/user/ssodata_ endpoint?

**Comment by MaSattari** [comment]
@landonreed , thank you for your response.

I've already pulled several branches from https://github.com/catalogueglobal/datatools-ui. The problem is that I am getting signed out immediately after sign in. There is an "Authorize" problem with "/userinfo" as shown here:

![conveyal logout error](https://user-images.githubusercontent.com/25766089/37340927-c5914d5c-26d0-11e8-939c-58811227a720.jpg)

![conveyal logout error detail](https://user-images.githubusercontent.com/25766089/37341200-9c5086a0-26d1-11e8-9120-ea795865e421.jpg)


I am following [PR](https://github.com/catalogueglobal/datatools-ui/pull/12) to get the latest merge.

Thank you.
