### ISSUE TITLE
Setting Up Auth0

### ISSUE THREAD

**Issue by pranavpandey1998official** [ibi-group/datatools-ui#592]
I just sucessfully setup auth0, I think this might help someone if he tries to do the same ,
1.  follow all the steps given in the docs( https://data-tools-docs.ibi-transit.com/en/dev/dev/deployment/) with few changes
a. `Use Auth0 instead of the IdP to do Single Sign On` this option doesn't exist
b. It says to give http://localhost:9000 or whatever your application domain is, don't give localhost as your domain , for me it doesn't work, if you are starting with yarn start it is proxied to http://192.168.29.246:9966/ give that 
c. make sure application type is machine to machine
d. in allow callback URL add http://192.168.29.246:9966/login too (so url with /login )
e. for auth token follow this and get the test token https://auth0.com/docs/api/management/v2/tokens

**Comment by landonreed** [comment]
Hi @pranavpandey1998official, if you have suggestions for improving the documentation, we're open to pull requests to improve this. 

Just a heads up, the IP address you've listed is likely just your localhost. If localhost is not working, there's probably some other issue preventing this. I would recommend not using the IP address for local development because often these are dynamically assigned (so next time you connect to your wifi network, you'll end up needing to change the IP address in the Auth0 settings).
