### ISSUE TITLE
Users Administation - /api/manager/secure/usercount returns 404

### ISSUE THREAD

**Issue by thomasrm** [ibi-group/datatools-ui#639]
Hi all,

I am having a 404 error for the URL  /api/manager/secure/usercount when on the Users Administration page. All the other API calls are returning correct responses.
As a consequence, the users aren't displayed and I don't seem to be able to add new ones. 

Any help would be greatly appreciated!

Cheers,
Thomas

**Comment by landonreed** [comment]
Hi @thomasrm, it would be helpful in debugging if you could share the server logs when the UI makes the usercount request. This is most likely an issue with something being misconfigured in datatools-server.

**Comment by thomasrm** [comment]
Thanks  for your reply @landonreed,

After looking into the logs, it turns out the AUTH0_API_CLIENT and AUTH0_API_SECRET were missing from my env.yml! I think I got confused with the deployment doc and believed they were not used anymore. 

FYI, the note I misunderstood is the following one: 

> Note: for older Auth0 accounts/tenants, it is possible to use the Auth0 secret token, which uses the HS256 algorithm, but newer Auth0 tenants will need to specify the absolute path of their .pem file in the AUTH0_PUBLIC_KEY property. This public key only needs to be downloaded one time for your Auth0 tenant at https://[your_domain].auth0.com/pem.

Both are added and the users management is now working!

Thanks for your help anyway!

**Comment by landonreed** [comment]
Happy to help, @thomasrm! Sorry for the confusing config around Auth0. That section probably needs a bit of a refresh.

**Comment by wkulesza** [comment]
@thomasrm I have both  AUTH0_TOKEN and AUTH0_SECRET and still getting that 404 error for /api/manager/secure/usercount. Would you be able to provide some hints on that ?

**Comment by changtung** [comment]
I have version of an app from dev branch. in env.yml in datatools-server there is AUTH0_API_CLIENT, AUTH0_API_SECRET provided. Also AUTH0_PUBLIC_KEY path in Docker container. There is also AUTH0_TOKEN and AUTH0_SECRET . When i do to admin panel i receive in datatools-server docker logs: 
`res (401) no-auth GET: http://localhost:8081/api/manager/secure/servers 
{
  "result" : "ERR",
  "message" : "Could not verify user's token",
  "code" : 401,
  "detail" : null
}
In AUTH0Connection.java there is an exception: 
java.lang.IllegalStateException: PublicKey cannot be null when using algorithm: SHA256withRSA
	at com.auth0.jwt.JWTVerifier.verifyRs(JWTVerifier.java:154)
	at com.auth0.jwt.JWTVerifier.verifySignature(JWTVerifier.java:133)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:110)
	at com.conveyal.datatools.manager.auth.Auth0Connection.checkUser(Auth0Connection.java:82)
However it cannot be null. `
Is this something with AUTH0 configuration or do i miss something in env.yml ? Because i assume that code works fine. 
Thank You
