### ISSUE TITLE
Support for Extended GTFS Route Types

### ISSUE THREAD

**Issue by mvanlaar** [ibi-group/datatools-ui#645]
_**NOTE:** This issue system is intended for reporting bugs and tracking progress in software development. Although this software is licensed with an open-source license, any issue opened here may not be responded to in a timely manner. [Conveyal](https://www.conveyal.com) is unable to provide technical support for custom deployments of this software unless your company has a support contract with us. Please remove this note when creating the issue._

## Observed behavior (please include a screenshot if possible)

No support for creating and editing routes with Extended GTFS Route Types

## Expected behavior

Support for editing Extended GTFS Route Types

## Steps to reproduce the problem

I would like to create 1500 Water Taxi Service and 1000 Water Transport Service route types. 

## Any special notes on configuration used

none

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

UI Version: | 872d61
Server version: | 11e9a8

Is the support for Extended GTFS Route Types on the roadmap? Or is as simple as editing the .yml config files and creating a pull request for this?

**Comment by landonreed** [comment]
Hi @mvanlaar, there is support for this in datatools-server:

https://github.com/conveyal/gtfs-lib/blob/048778369dd9d62180fd01cd403b30f9d0ce6966/src/main/java/com/conveyal/gtfs/loader/Table.java#L178-L180

But you're correct in that the UI does not support these values in the Editor. I hesitate to simply update the `gtfs.yml` file with all of the extended route types (or even just cherry-picking a few), just because they are less commonly used and would complicate that form element for most users. Another approach (though this complicates the implementation) would be to show the primary options and allow custom input for values between, say, 13 and 1800. This issue also highlights that the `routes#route_type`field in `gtfs.yml` is missing values 8 through 12, which have already been incorporated into the GTFS spec.

I'll take a look at the code and will update this ticket with more info.

**Comment by mvanlaar** [comment]
I've added in my local copy the google supported values. Thats working.

**Comment by mvanlaar** [comment]
We could try to make it a optgroup for the primary values and a optgroup for the secondary options.

**Comment by mvanlaar** [comment]
Is this something that we can use also for the fares? #551 #566 ? Because this more of the same, larger list that are supported but you want sometimes to show only a portion.
